// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	User  *User  `json:"user"`
	Token string `json:"token"`
}

type AuthToken struct {
	Token string `json:"token"`
}

type EmailToken struct {
	Token string `json:"token"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewPost struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Post struct {
	ID        string `json:"id"`
	Text      string `json:"text"`
	Published bool   `json:"published"`
	User      *User  `json:"user"`
}

type Register struct {
	Email    string  `json:"email"`
	Username string  `json:"username"`
	Password string  `json:"password"`
	FullName *string `json:"fullName,omitempty"`
	Avatar   *string `json:"avatar,omitempty"`
}

type Update struct {
	Username *string `json:"username,omitempty"`
	FullName *string `json:"fullName,omitempty"`
	Password *string `json:"password,omitempty"`
	Avatar   *string `json:"avatar,omitempty"`
}

type User struct {
	ID            string  `json:"id"`
	Email         string  `json:"email"`
	Username      string  `json:"username"`
	Password      string  `json:"password"`
	FullName      *string `json:"fullName,omitempty"`
	Avatar        *string `json:"avatar,omitempty"`
	EmailVerified *bool   `json:"emailVerified,omitempty"`
	CreatedAt     string  `json:"createdAt"`
	Posts         []*Post `json:"posts"`
}
